"""Create linked test data through the endpoints in postman_collection.json.

Authentication endpoints are deliberately skipped. Paste an existing ADMIN
bearer token at the terminal prompt; it is never stored in this file.
"""

from __future__ import annotations

import argparse
import getpass
import json
import secrets
import sys
import time
from dataclasses import asdict, dataclass, field
from datetime import datetime, timedelta, timezone
from typing import Any

import requests


DEFAULT_BASE_URL = "http://172.31.20.206:30001/api/v1"


class AutomationError(RuntimeError):
    pass


@dataclass
class CreatedData:
    run: int
    origin_station_public_id: str = ""
    destination_station_public_id: str = ""
    train_public_id: str = ""
    route_public_id: str = ""
    schedule_public_id: str = ""
    seat_public_id: str = ""
    booking_code: str = ""
    payment_reference: str = ""
    ticket_numbers: list[str] = field(default_factory=list)


class TicketApi:
    def __init__(self, base_url: str, token: str, timeout: int) -> None:
        self.base_url = base_url.rstrip("/")
        self.timeout = timeout
        self.session = requests.Session()
        self.session.headers.update({
            "Authorization": f"Bearer {token}",
            "Content-Type": "application/json",
            "Accept": "application/json",
        })

    def request(self, method: str, path: str, payload: dict[str, Any] | None = None,
                headers: dict[str, str] | None = None) -> Any:
        url = f"{self.base_url}/{path.lstrip('/')}"
        try:
            response = self.session.request(
                method, url, json=payload, headers=headers, timeout=self.timeout
            )
        except requests.RequestException as exc:
            raise AutomationError(f"{method} {url} failed: {exc}") from exc

        try:
            body = response.json()
        except ValueError:
            body = response.text
        if not response.ok:
            rendered = body if isinstance(body, str) else json.dumps(body, ensure_ascii=False)
            raise AutomationError(
                f"{method} {url} returned HTTP {response.status_code}: {rendered}"
            )
        if isinstance(body, dict) and body.get("success") is False:
            raise AutomationError(f"{method} {url} was unsuccessful: {body}")
        return body.get("data") if isinstance(body, dict) and "data" in body else body

    def close(self) -> None:
        self.session.close()


def required(data: Any, key: str, step: str) -> Any:
    if not isinstance(data, dict) or not data.get(key):
        raise AutomationError(f"{step} response has no '{key}': {data}")
    return data[key]


def create_dataset(api: TicketApi, run: int, args: argparse.Namespace) -> CreatedData:
    result = CreatedData(run=run)
    unique = f"{int(time.time() * 1000):x}{secrets.token_hex(2)}{run}"
    short = unique[-10:].upper()

    def step(label: str, method: str, path: str,
             payload: dict[str, Any] | None = None,
             headers: dict[str, str] | None = None) -> Any:
        print(f"  - {label} ... ", end="", flush=True)
        data = api.request(method, path, payload, headers)
        print("OK")
        return data

    origin = step("create origin station", "POST", "/stations", {
        "code": f"O{short}", "name": f"Automation Origin {short}",
        "city": "Jakarta", "province": "DKI Jakarta",
        "address": "Generated by automation-bookings.py", "timezone": "Asia/Jakarta",
    })
    result.origin_station_public_id = required(origin, "publicId", "origin station")

    destination = step("create destination station", "POST", "/stations", {
        "code": f"D{short}", "name": f"Automation Destination {short}",
        "city": "Bandung", "province": "Jawa Barat",
        "address": "Generated by automation-bookings.py", "timezone": "Asia/Jakarta",
    })
    result.destination_station_public_id = required(destination, "publicId", "destination station")

    train = step("create train", "POST", "/trains", {
        "trainCode": f"KA-AUTO-{short}", "name": f"Automation Express {short}",
        "trainClass": "ECONOMY",
        "totalSeats": args.carriages * args.seats_per_carriage,
    })
    result.train_public_id = required(train, "publicId", "train")

    seats = step("generate seats", "POST",
                 f"/trains/{result.train_public_id}/seats/generate", {
        "carriages": args.carriages, "seatsPerCarriage": args.seats_per_carriage,
        "seatClass": "ECONOMY",
    })
    if not isinstance(seats, list) or not seats:
        raise AutomationError(f"generate seats response contains no seats: {seats}")
    result.seat_public_id = required(seats[0], "publicId", "generate seats")

    route = step("create route", "POST", "/routes", {
        "routeCode": f"RT-AUTO-{short}",
        "originStationPublicId": result.origin_station_public_id,
        "destinationStationPublicId": result.destination_station_public_id,
        "distanceKm": 150.5, "estimatedDurationMinutes": 180,
    })
    result.route_public_id = required(route, "publicId", "route")

    departure = (datetime.now(timezone.utc) + timedelta(days=7 + run)).replace(
        hour=1, minute=0, second=0, microsecond=0
    )
    schedule = step("create schedule", "POST", "/schedules", {
        "scheduleCode": f"SCH-AUTO-{short}",
        "trainPublicId": result.train_public_id,
        "routePublicId": result.route_public_id,
        "departureTime": departure.isoformat().replace("+00:00", "Z"),
        "arrivalTime": (departure + timedelta(hours=3)).isoformat().replace("+00:00", "Z"),
        "basePrice": args.base_price,
    })
    result.schedule_public_id = required(schedule, "publicId", "schedule")

    booking = step("create booking", "POST", "/bookings", {
        "schedulePublicId": result.schedule_public_id,
        "seats": [{
            "seatPublicId": result.seat_public_id,
            "passenger": {
                "fullName": f"Automation Passenger {run}", "identityType": "KTP",
                "identityNumber": f"3174{int(time.time() * 1000)}{run}",
                "dateOfBirth": "1998-01-01", "passengerType": "ADULT",
            },
        }],
    })
    result.booking_code = required(booking, "bookingCode", "booking")

    payment = step("create payment", "POST",
                   f"/bookings/{result.booking_code}/payments", {
        "paymentMethod": "BANK_TRANSFER", "amount": args.base_price,
    })
    result.payment_reference = required(payment, "paymentReference", "payment")

    if not args.skip_payment_confirmation:
        confirmation = step(
            "confirm payment and issue ticket", "POST",
            f"/payments/{result.payment_reference}/confirm", None,
            {"idempotency-key": f"automation-{unique}"},
        )
        tickets = confirmation.get("tickets", []) if isinstance(confirmation, dict) else []
        result.ticket_numbers = [
            ticket["ticketNumber"] for ticket in tickets
            if isinstance(ticket, dict) and ticket.get("ticketNumber")
        ]
    return result


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Create linked ticket-booking data using the Postman API flow."
    )
    parser.add_argument("--base-url", default=DEFAULT_BASE_URL)
    parser.add_argument("--runs", type=int, default=1, help="Datasets to create")
    parser.add_argument("--carriages", type=int, default=1)
    parser.add_argument("--seats-per-carriage", type=int, default=4)
    parser.add_argument("--base-price", type=float, default=250000)
    parser.add_argument("--timeout", type=int, default=30)
    parser.add_argument("--skip-payment-confirmation", action="store_true",
                        help="Leave payments pending and do not issue tickets")
    args = parser.parse_args()
    for name in ("runs", "carriages", "seats_per_carriage", "timeout"):
        if getattr(args, name) < 1:
            parser.error(f"--{name.replace('_', '-')} must be at least 1")
    if args.base_price <= 0:
        parser.error("--base-price must be greater than zero")
    return args


def main() -> int:
    args = parse_args()
    print("Ticket API data-creation automation")
    print(f"Base URL: {args.base_url}")
    token = getpass.getpass("Paste ADMIN bearer token (input hidden): ").strip()
    if token.lower().startswith("bearer "):
        token = token[7:].strip()
    if not token:
        print("Error: a bearer token is required.", file=sys.stderr)
        return 2

    api = TicketApi(args.base_url, token, args.timeout)
    created: list[CreatedData] = []
    failures: list[dict[str, Any]] = []
    started = time.perf_counter()
    try:
        for run in range(1, args.runs + 1):
            print(f"\nDataset {run}/{args.runs}")
            try:
                created.append(create_dataset(api, run, args))
            except AutomationError as exc:
                failures.append({"run": run, "error": str(exc)})
                print(f"  FAILED: {exc}", file=sys.stderr)
    finally:
        api.close()

    print("\nSummary")
    print(json.dumps({
        "elapsedSeconds": round(time.perf_counter() - started, 2),
        "successfulDatasets": len(created), "failedDatasets": len(failures),
        "created": [asdict(item) for item in created], "failures": failures,
    }, indent=2, ensure_ascii=False))
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
