services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ticket-app
    ports:
      - '3001:3000'
    environment:
      NODE_ENV: development
      PORT: 3000
      API_PREFIX: api
      API_VERSION: v1
      CORS_ORIGINS: http://localhost:3000
      SWAGGER_ENABLED: 'true'
      BOOKING_HOLD_MINUTES: 10
      DATABASE_URL: postgresql://postgres:postgres@host.docker.internal:5432/ticket_app?schema=public
      JWT_ACCESS_SECRET: change-me-access-secret
      JWT_ACCESS_EXPIRES_IN: 15m
      JWT_REFRESH_SECRET: change-me-refresh-secret
      JWT_REFRESH_EXPIRES_IN: 7d
      BCRYPT_SALT_ROUNDS: 12
    restart: unless-stopped
